os: linux
dist: bionic
language: go
go:
  - "1.16"

cache:
  directories:
    - "$GOPATH/pkg/mod"

install:
  - make install

script:
  - make test
  - make build

before_deploy:
  - make build-release

deploy:
  provider: releases
  api_key:
    secure: Fn1MdiXY2fi5jPwQMjp9T/oxW6slwaM1OkHifYFjEN1EoX5J5IZcNB74YGEyJpxNtbX9Mr1yxMbmr2LEVluCaQ29CRiVvauTE5qsdKOTzlTc8QX4D+cJY5xFchfAbmLAZ287RkH8JaFLjjk0rV3ZmJ+WyWNXYhTuOloZmeXmwJyZ/ZiJ0f70K3x641JkL5mIOvpDbNG93tVu2rXsKd5LALNmbtr3wPNOr2zqmYc9pF9GpfznGQugIyvCDqmfuXZrNHixBQXs6yZYCTn3jsiZcbfeHRj4Bpoy5AHudDrsRf0hfB5NUEDyP2vgoOt4LpygrmvpAUxL5jI8sZc03BjnkDguth0NZyJXMYVmU02wYHYYswzLIfwYpGZWAiVdYBz9lnLKrif2PwMAzhb/QRsvDKM3Hpv6/cHofCYptFHL0pzrMENTFICgnWnzKYdedUnlX4a2I0VWFqpGZv9IXhjxWqzZk2+DSMHR2i1G1g4tdoeDT9UabNaTfwPdwedXoXq7yn11gk2CVUjiTe5+yeOQ2HlNYyK44cqB9kyRJQSVNkm3cSm+NrSAJc6/G9YRJTngrY5jKcxQ8m7ZByYl6Gh/xVj/Vf+DikI5ILLMaqwRz16oWEI2RBMaVa7Vve4Xq0S8t0DWeLtR2DUvFGJWSIiwzJhJqj+pZNgl4pYhyP1hifo=
  file_glob: true
  file: pkg/*
  skip_cleanup: true
  on:
    tags: true
